create table public.leads (
  id                    uuid        primary key default gen_random_uuid(),
  customer_id           uuid        references public.customers(id),
  source                text,
  brand                 text,
  authority             text,
  status                text        not null default 'Pending',
  sales_status          text,
  is_inbox              boolean     not null default true,
  sdr_id                uuid        references auth.users(id),
  assigned_sdr_id       uuid        references auth.users(id),
  sales_owner_id        uuid        references auth.users(id),
  held_by_id            uuid        references auth.users(id),
  interests             jsonb       not null default '{}',
  quantities            jsonb       not null default '{}',
  quote_total           numeric,
  quote_channel         text,
  quote_destination     text,
  hold_reason           text,
  hold_notes            text,
  hold_until            timestamptz,
  held_at               timestamptz,
  prev_status           text,
  prev_sales_status     text,
  urgency               text        check (urgency in ('High', 'Medium', 'Low')),
  is_returning_customer boolean     not null default false,
  sdr_comment           text,
  rejection_reason      text,
  rejection_notes       text,
  locked_by_id          uuid        references auth.users(id),
  locked_at             timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
