create table public.job_tickets (
  id                                 uuid        primary key default gen_random_uuid(),
  ticket_kind                        text        not null check (ticket_kind in ('quote', 'order')),
  ticket_status                      text        not null default 'draft',
  customer_id                        uuid        references public.customers(id),
  linked_lead_id                     uuid        references public.leads(id),
  created_by_id                      uuid        references auth.users(id),
  contact_email                      text,
  contact_name                       text,
  contact_company                    text,
  subtotal                           numeric,
  discount_percent                   numeric,
  discount_amount                    numeric,
  total                              numeric,
  payment_type                       text,
  prepay_amount                      numeric,
  product_lines                      jsonb       not null default '[]',
  quote_skus                         jsonb       not null default '[]',
  rush                               boolean     not null default false,
  follow_up_at                       timestamptz,
  follow_up_completed                boolean     not null default false,
  client_confirmed                   boolean     not null default false,
  quote_approval_last_requested_at   timestamptz,
  notes                              text,
  created_at                         timestamptz not null default now(),
  updated_at                         timestamptz not null default now()
);
